openapi: 3.1.0
info:
  title: VISO TRUST API Documentation client-api-assessment-rest-resource client-api-data-type-rest-resource API
  description: VISO TRUST
  version: v1.0
servers:
- url: https://app.visotrust.com
  description: VISO TRUST production API
security:
- bearerAuth: []
tags:
- name: client-api-data-type-rest-resource
paths:
  /api/v1/data-types:
    get:
      tags:
      - client-api-data-type-rest-resource
      summary: Get all data types for your organization.
      operationId: getAllDataTypesForCurrentClient
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DataTypeView'
components:
  schemas:
    DataTypeView:
      type: object
      properties:
        description:
          type: string
        name:
          type: string
      required:
      - name
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      description: API token generated from your VISO TRUST user profile. Send it in the `Authorization` header as `Bearer <token>`.
externalDocs:
  description: VISO TRUST Support Documentation
  url: https://support.visotrust.com/
